export const INITIAL_PAGE_SIZE = 20;
export const SCROLL_PAGE_SIZE = 20;
export const MAX_RENDERED_MESSAGES = 80;
export const TRIM_TO_MESSAGES = 60;
export const MAX_RUNTIME_MESSAGES_PER_CONVERSATION = 180;
export const MAX_RUNTIME_MEASURED_HEIGHTS_PER_CONVERSATION = 360;
export const MAX_LOCAL_CACHED_MESSAGES_PER_CONVERSATION = 300;

export const MESSAGE_INITIAL_PAGE_SIZE = INITIAL_PAGE_SIZE;
export const MESSAGE_PAGE_SIZE = SCROLL_PAGE_SIZE;
export const MESSAGE_CACHE_LIMIT = MAX_LOCAL_CACHED_MESSAGES_PER_CONVERSATION;
export const MESSAGE_ACTIVE_WINDOW_SIZE = TRIM_TO_MESSAGES;
export const MAX_CACHED_MESSAGES_PER_CONVERSATION = MAX_LOCAL_CACHED_MESSAGES_PER_CONVERSATION;
export const MAX_ACTIVE_CONVERSATIONS = 8;
export const FALLBACK_MESSAGE_HEIGHT = 72;
export const MESSAGE_WINDOW_TRIM_TRIGGER = MAX_RENDERED_MESSAGES;
export const MESSAGE_WINDOW_TRIM_TARGET = TRIM_TO_MESSAGES;

// Viewport-informed initial open constants — used only for the first local-read
// window when opening a conversation, NOT for sync or pagination.
export const MIN_MESSAGE_ROW_HEIGHT_PX = 44;
export const VIEWPORT_FILL_BUFFER = 10;
export const MAX_INITIAL_OPEN_COUNT = 60;
