export const OP = {
  EVENT: 0,
  HEARTBEAT: 1,
  IDENTIFY: 2,
  HEARTBEAT_ACK: 3,
  STATUS_UPDATE: 4,
  RESUME: 6,
  RESUMED: 7,
  HELLO: 10,
};

export const EVENTS = {
  READY: 'READY',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  FRIEND_ACCEPT: 'FRIEND_ACCEPT',
  FRIEND_REMOVE: 'FRIEND_REMOVE',
  PRESENCE_UPDATE: 'PRESENCE_UPDATE',
  CONVERSATION_UPDATE: 'CONVERSATION_UPDATE',
  SELF_LEAVE_ROTATION_REQUIRED: 'SELF_LEAVE_ROTATION_REQUIRED',
  MEMBER_NICKNAME_UPDATE: 'MEMBER_NICKNAME_UPDATE',
  MESSAGE_CREATE: 'MESSAGE_CREATE',
  TYPING_START: 'TYPING_START',
  TOKEN_EXPIRING: 'TOKEN_EXPIRING',
  REACTION_ADD: 'REACTION_ADD',
  REACTION_REMOVE: 'REACTION_REMOVE',
  REACTIONS_BATCH: 'REACTIONS_BATCH',
  DM_HIDDEN: 'DM_HIDDEN',
};

export const CLOSE = {
  AUTH_TIMEOUT: 4000,
  UNAUTHORIZED: 4001,
  PROTOCOL_ERROR: 4002,
  FORBIDDEN: 4003,
  INVALID_SESSION: 4007,
  RATE_LIMITED: 4008,
  SESSION_REPLACED: 4009,
  SLOW_CONSUMER: 4010,
};
